server:
  port: 7001
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    config:
      server:
        git:
          uri: