server:
  port: 7001
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dongfangYH/microservice.git
          search-paths: SC-CONFIG