server:
  port: 8001
eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always