
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
    register-with-eureka: true
    fetch-registry: false
spring:
  application:
    name: plainService