
#server:
#  port: 9003
#  servlet:
#    context-path: /plain-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
    register-with-eureka: true
    fetch-registry: false
spring:
  profiles:
    active: dev1
  application:
    name: plainService

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true

---

eureka:
  instance:
    metadata-map:
      host-mark: running-host
server:
  port: 9004
spring:
  profiles: dev1
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      max-lifetime: 10000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 10
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---

server:
  port: 9005
spring:
  profiles: dev2

eureka:
  instance:
    metadata-map:
      host-mark: gray-host
